### ISSUE TITLE
update markdown cli

### ISSUE THREAD

**Issue by chicco785** [SmartInfrastructures/guided-tour-builder#1]
hi @dancn 
if you rebuild the image, the new version of markdownlint-cli should be fixing the issues we had with code in lists.

cheers

**Comment by dancn** [comment]
Hi @chicco785,

I pushed the repo under the smartsdk namespace, with automatic build in place few mins ago.

Will also update the guided tour https://github.com/smartsdk/guided-tour

and delete this repo and my personal docker image soon to avoid confusion.

Best
